linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - exhaustruct
    - funlen
    - gochecknoglobals
    - golint
    - ifshort
    - interfacer
    - lll
    - maligned
    - nlreturn
    - scopelint
    - varnamelen
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - noctx

linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US
